<?php

class AIEagleAutoGenerator
{
    public function message($status){
        $messages = [
            'Approve' => [
                "The requisition aligns perfectly with our operational needs.",
                "Great justification provided for the requested items.",
                "The budget is clearly outlined and justified.",
                "Well done on identifying necessary suppliers.",
                "All required documentation is complete and accurate.",
                "The proposed timeline for delivery is reasonable.",
                "This requisition demonstrates effective stakeholder engagement.",
                "The requested items will enhance our productivity.",
                "Thorough analysis of costs is commendable.",
                "The request supports our strategic goals effectively.",
                "I appreciate the detailed explanation of needs.",
                "Supplier selection criteria are well defined.",
                "The plan for monitoring progress is robust.",
                "The focus on quality in the requisition is commendable.",
                "Excellent consideration of sustainability factors.",
                "The risk assessment is comprehensive and thoughtful.",
                "Good job on anticipating potential challenges.",
                "The communication strategy with suppliers is clear.",
                "The inclusion of performance metrics is a smart touch.",
                "I support this requisition with confidence.",
                "Great collaboration shown in preparing this request.",
                "The clarity of roles and responsibilities is impressive.",
                "This requisition is well-structured and easy to understand.",
                "Good foresight in addressing potential supply chain issues.",
                "I appreciate the emphasis on ethical sourcing.",
                "The training requirements for implementation are well thought out.",
                "The requisition meets all compliance standards.",
                "The detailed vendor evaluation process is reassuring.",
                "I'm impressed with the thoroughness of the research.",
                "The proposed items will significantly benefit our operations.",
                "I value the focus on long-term sustainability.",
                "This requisition demonstrates a proactive approach.",
                "Excellent work on creating a compelling case for approval.",
                "The contingency plans outlined are comprehensive.",
                "The attention to detail in the cost breakdown is commendable.",
                "I appreciate the thoughtful consideration of alternatives.",
                "The timeline allows for proper execution and planning.",
                "Good job on engaging all necessary stakeholders.",
                "The budget reflects fiscal responsibility.",
                "The focus on technological advancements is commendable.",
                "The overall strategy is clear and actionable.",
                "This requisition is a significant step forward for our team.",
                "I support the proposed suppliers based on their credentials.",
                "The plan includes a well-defined evaluation process.",
                "Excellent communication regarding objectives and needs.",
                "The request demonstrates thorough market analysis.",
                "I appreciate the innovative solutions presented.",
                "The environmental considerations are well articulated.",
                "I'm confident in the successful implementation of this requisition.",
                "This requisition is a strong addition to our project plans.",
                "The alignment with our organizational goals is evident.",
                "I'm pleased with the depth of analysis provided.",
                "The request is timely and necessary for our operations.",
                "I commend the effort put into this requisition.",
                "This will lead to improved efficiency in our processes."
            ],
            'Reject' => [
                "The requisition lacks sufficient justification for the requested items.",
                "Budget constraints make this request unfeasible.",
                "There are gaps in the documentation provided.",
                "Supplier selection is not adequately addressed.",
                "The timeline for delivery is unrealistic.",
                "Stakeholder engagement appears minimal.",
                "The risk assessment is insufficient for approval.",
                "Quality control measures are not defined clearly.",
                "The request does not align with our strategic objectives.",
                "The proposed items are not critical to operations.",
                "Cost analysis lacks supporting data.",
                "There are concerns regarding vendor reliability.",
                "The focus on sustainability is lacking.",
                "Alternatives to the requested items were not considered.",
                "The communication plan with suppliers is vague.",
                "Performance metrics are not well defined.",
                "The requisition is missing essential compliance information.",
                "The need for these items is not adequately explained.",
                "The overall structure of the request is confusing.",
                "The budget does not reflect actual costs.",
                "There are no contingency plans in place.",
                "The request appears to have insufficient research backing.",
                "Immediate needs were not properly assessed.",
                "This requisition fails to identify potential challenges.",
                "The environmental impact is not adequately considered.",
                "The evaluation process for vendors is lacking rigor.",
                "I cannot support this requisition in its current form.",
                "The focus on long-term value is insufficient.",
                "There is a lack of clarity in roles and responsibilities.",
                "Stakeholder feedback is missing from this request.",
                "The plan for implementation is underdeveloped.",
                "The overall strategy does not support our goals.",
                "The timeline for implementation is overly ambitious.",
                "The proposed suppliers have questionable backgrounds.",
                "The requisition lacks alignment with budget priorities.",
                "Quality requirements are not adequately specified.",
                "The request is incomplete and needs further details.",
                "The cost-benefit analysis is not convincing.",
                "I cannot support this plan without major revisions.",
                "There are unresolved issues regarding compliance.",
                "The requisition is not aligned with current projects.",
                "The need for these items is not urgent enough.",
                "Insufficient justification for the urgency of this request.",
                "The environmental considerations are inadequate.",
                "This procurement strategy needs a complete rethink.",
                "The focus on innovation is missing.",
                "The plan is missing essential approval signatures."
            ],
            'RequestMoreInformation' => [
                "The requisition shows potential but needs more detail.",
                "Budget implications require further evaluation.",
                "More clarity is needed regarding the requested items.",
                "Supplier evaluation criteria should be revisited.",
                "Further stakeholder feedback is essential.",
                "The timeline may need adjustments for feasibility.",
                "Consider expanding the focus on sustainability.",
                "Additional justification for costs is required.",
                "The communication strategy could be strengthened.",
                "A more thorough risk assessment is necessary.",
                "Awaiting further details on vendor reliability.",
                "The overall structure of the requisition needs refinement.",
                "Assess the immediate needs more thoroughly.",
                "Clarify the roles and responsibilities involved.",
                "The plan for monitoring progress is vague.",
                "Review the alignment with strategic objectives.",
                "Provide better justification for the urgency of the request.",
                "Enhance transparency in the budgeting process.",
                "The plan lacks detail on implementation.",
                "Further analysis of alternative options is needed.",
                "Review environmental impacts more thoroughly.",
                "Include a detailed contingency plan.",
                "The focus on quality control requires more depth.",
                "The budget proposal needs additional support.",
                "More details are needed on the vendor evaluation process.",
                "Clarify performance metrics for success.",
                "Evaluate the potential risks in more detail.",
                "The strategic alignment needs to be clearer.",
                "Further detail is required for the training component.",
                "Consider integrating recent market findings.",
                "The timeline for delivery requires closer scrutiny.",
                "Review the focus on technological advancements.",
                "More information is needed on stakeholder engagement.",
                "Assess the long-term implications of this requisition.",
                "Clarify the cost breakdown for all items requested.",
                "Review the communication plan for better stakeholder engagement.",
                "Ensure all compliance standards are addressed.",
                "Provide a more detailed evaluation process.",
                "Identify potential challenges more clearly.",
                "The overall strategy should align better with current goals.",
                "Further discussion is needed on the implementation timeline.",
                "Strengthen the justification for the requested items.",
                "Review the proposed suppliers for reliability.",
                "Enhance the overall presentation of the requisition.",
                "Include a detailed market analysis.",
                "Ensure all critical aspects of the requisition are covered.",
                "Seek additional input from relevant stakeholders."
            ],
            'OnHold' => [
                "The requisition requires further information before proceeding.",
                "Pending clarification on budgetary implications.",
                "Awaiting feedback from stakeholders for final approval.",
                "Further analysis of supplier options is needed.",
                "Need additional details on the proposed timeline.",
                "Hold for further assessment of compliance requirements.",
                "Pending updates on project priorities.",
                "Waiting for market research results.",
                "Need to clarify roles and responsibilities involved.",
                "Decision is contingent on additional stakeholder input.",
                "The request requires further justification.",
                "Hold until vendor reliability is confirmed.",
                "Pending final approval from upper management.",
                "Need to address outstanding questions from the review team.",
                "The requisition will remain on hold until further notice.",
                "Further discussion is needed regarding sustainability considerations.",
                "Awaiting completion of necessary training sessions.",
                "The budget proposal needs additional validation.",
                "Hold for a review of the overall procurement strategy.",
                "Pending the outcome of ongoing negotiations with suppliers.",
                "Further details are needed to evaluate risks involved.",
                "Awaiting stakeholder feedback on urgent needs.",
                "The plan will be on hold until all compliance checks are complete.",
                "Additional analysis of environmental impacts is required.",
                "Need to confirm the urgency of the request.",
                "The overall strategy requires re-evaluation before moving forward.",
                "Hold for additional market analysis.",
                "The communication plan with suppliers needs clarification.",
                "Pending further details on implementation logistics.",
                "The requisition requires a complete review of the current needs.",
                "Hold until all necessary documentation is submitted.",
                "Further discussion needed on potential challenges.",
                "The request will remain on hold pending approvals.",
                "Awaiting feedback from the legal department.",
                "Need to reassess the procurement timeline based on recent developments.",
                "The requisition requires a thorough review before moving forward.",
                "Hold for more information regarding training needs.",
                "Need further clarification on the requested items' specifications.",
                "Awaiting updates on internal budget allocations.",
                "The requisition is on hold until all conditions are met.",
                "Pending additional assessments of supplier options."
            ]
        ];
        
            
        // Validate the status
        if (!isset($messages[$status])) {
            return response()->json(['error' => 'Invalid status'], 400);
        }

        // Get random 5 messages
        $selectedMessages = self::getRandomMessages($messages[$status], 5);

        echo json_encode($selectedMessages);
        
    }

    public static function getRandomMessages($messagesArray, $numMessages) {
        $keys = array_rand($messagesArray, min($numMessages, count($messagesArray))); // Get random keys
        if (!is_array($keys)) {
            $keys = [$keys]; // Ensure $keys is always an array
        }
        return array_map(function($key) use ($messagesArray) {
            return $messagesArray[$key];
        }, $keys);
    }
}

$status = $_GET['status'] ?? 'approve';

AIEagleAutoGenerator::message($status);
