<?php

function static_pool_vehicle_driver(){ 	return 29; }
function static_person_to_holder(){ return 37; }
function static_hod_id(){ 	return 34; }
function static_vehicle_type(){ return 1; }
function static_office(){ return 9;}
function static_transport_officer( ){ return 32; }
function static_accounts_officer(){ return 33; }
function static_md() { return 31; }
function static_territory_driver(){ return 39; }
function static_hr_and_admin(){ return 44; }
function static_cfo(){ return 30; }
function static_super(){ return 35; }
function static_hos(){ return 36; }
function static_area_manager(){ return 41; }
function static_person_to_holder_vehicle_user(){ return 46;}